-- MySQL Script generated by MySQL Workbench
-- Sun Apr  6 19:22:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ParkingLot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ParkingLot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ParkingLot` DEFAULT CHARACTER SET utf8 ;
USE `ParkingLot` ;

-- -----------------------------------------------------
-- Table `ParkingLot`.`PERFIL_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`PERFIL_USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `primer_nombre` VARCHAR(255) NOT NULL,
  `segundo_nombre` VARCHAR(225) NULL,
  `primer_apellido` VARCHAR(255) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `direccion_correo` VARCHAR(255) NOT NULL,
  `numero_celular` VARCHAR(45) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `estado` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(255) NULL,
  `PERFIL_USUARIO_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `PERFIL_USUARIO_id`),
  INDEX `fk_USUARIO_PERFIL_USUARIO_idx` (`PERFIL_USUARIO_id` ASC) ,
  CONSTRAINT `fk_USUARIO_PERFIL_USUARIO`
    FOREIGN KEY (`PERFIL_USUARIO_id`)
    REFERENCES `ParkingLot`.`PERFIL_USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`VEHICULO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`, `USUARIO_id_usuario`),
  INDEX `fk_VEHICULO_USUARIO1_idx` (`USUARIO_id_usuario` ASC) ,
  CONSTRAINT `fk_VEHICULO_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `ParkingLot`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`PICO_PLACA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`PICO_PLACA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_vehiculo` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `dia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`ACCESO_SALIDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`ACCESO_SALIDAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movimiento` VARCHAR(45) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `puerta` VARCHAR(45) NULL,
  `tiempo_estadia` INT NULL,
  `VEHICULO_id` INT NOT NULL,
  PRIMARY KEY (`id`, `VEHICULO_id`),
  INDEX `fk_ACCESO_SALIDAS_VEHICULO1_idx` (`VEHICULO_id` ASC) ,
  CONSTRAINT `fk_ACCESO_SALIDAS_VEHICULO1`
    FOREIGN KEY (`VEHICULO_id`)
    REFERENCES `ParkingLot`.`VEHICULO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`INCIDENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`INCIDENCIA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`REPORTE_INCIDENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`REPORTE_INCIDENCIA` (
  `VEHICULO_id` INT NOT NULL,
  `INCIDENCIA_id` INT NOT NULL,
  `fecha_hora` DATETIME NULL,
  PRIMARY KEY (`VEHICULO_id`, `INCIDENCIA_id`),
  INDEX `fk_VEHICULO_has_INCIDENCIA_INCIDENCIA1_idx` (`INCIDENCIA_id` ASC) ,
  INDEX `fk_VEHICULO_has_INCIDENCIA_VEHICULO1_idx` (`VEHICULO_id` ASC) ,
  CONSTRAINT `fk_VEHICULO_has_INCIDENCIA_VEHICULO1`
    FOREIGN KEY (`VEHICULO_id`)
    REFERENCES `ParkingLot`.`VEHICULO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEHICULO_has_INCIDENCIA_INCIDENCIA1`
    FOREIGN KEY (`INCIDENCIA_id`)
    REFERENCES `ParkingLot`.`INCIDENCIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`CELDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`CELDA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingLot`.`HISTORIAL_PARQUEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingLot`.`HISTORIAL_PARQUEO` (
  `CELDA_id` INT NOT NULL,
  `VEHICULO_id` INT NOT NULL,
  `fecha_hora` DATETIME NULL,
  PRIMARY KEY (`CELDA_id`, `VEHICULO_id`),
  INDEX `fk_CELDA_has_VEHICULO_VEHICULO1_idx` (`VEHICULO_id` ASC) ,
  INDEX `fk_CELDA_has_VEHICULO_CELDA1_idx` (`CELDA_id` ASC) ,
  CONSTRAINT `fk_CELDA_has_VEHICULO_CELDA1`
    FOREIGN KEY (`CELDA_id`)
    REFERENCES `ParkingLot`.`CELDA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CELDA_has_VEHICULO_VEHICULO1`
    FOREIGN KEY (`VEHICULO_id`)
    REFERENCES `ParkingLot`.`VEHICULO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS

-- inserts para PERFIL_USUARIO
insert into PERFIL_USUARIO values (null, "administrador");
insert into PERFIL_USUARIO values (null, "operador");
insert into PERFIL_USUARIO values (null, "usuario");

-- Inserts para USUARIO
INSERT INTO USUARIO VALUES (null, 'CC', '651684841', 'Abel', '', 'Rivero', 'Herrera', 'abel.rivero@gmail.com', '561465151', 'img/abel.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '8947676234', 'Ada', 'Alicia', 'Rivero', 'herrera', 'ada.rivero@gmail.com', '897484561', 'img/ada.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 1);
INSERT INTO USUARIO VALUES (null, 'CC', '8947676234', 'Martha', 'Paola', 'Perez', 'Ospino', 'martha.perez@gmail.com', '897484561', 'img/Martha.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '756876875', 'Carlos', 'Manuel', 'Uran', 'Menodza', 'carlos.uran@gmail.com', '7866856', 'img/carlos.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 2);
INSERT INTO USUARIO VALUES (null, 'CC', '756876875', 'Maria', 'Del Carmen', 'Herrera', 'Alian', 'maria.herrera@gmail.com', '56154118', 'img/maria.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '894151', 'Peggy', 'Geraldine', 'Herrera', 'Alian', 'peggy.herrera@gmail.com', '8948484', 'img/peggy.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '7894484644', 'Esteban', 'Solarte', 'Jaramillo', 'Alian', 'esteban.solarte@gmail.com', '4851855', 'img/esteban.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '756876875', 'Maria', 'Del Carmen', 'Herrera', 'Alian', 'maria.herrera@gmail.com', '56154118', 'img/maria.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '894151', 'Peggy', 'Geraldine', 'Herrera', 'Alian', 'peggy.herrera@gmail.com', '8948484', 'img/peggy.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '7894484644', 'Esteban', 'Solarte', 'Jaramillo', 'Alian', 'esteban.solarte@gmail.com', '4851855', 'img/esteban.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '23151486', 'Amparo', '', 'Grisales', 'Londoño', 'amaparo.grisales@gmail.com', '7894844', 'img/amparo.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '6815158', 'Libardo', 'De Jesus', 'Atehortua', 'Grisales', 'libardo.atehortua@gmail.com', '12584181', 'img/libardo.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '8764554', 'Lincho', 'De Jesus', 'Alvarez', 'Otero', 'lincho.alvarez@gmail.com', '1868445', 'img/lincho.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 2);
INSERT INTO USUARIO VALUES (null, 'CC', '87897660', 'Melissa', '', 'Otero', 'Alvarez', 'mely.otero@gmail.com', '56615641468', 'img/melissa.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);
INSERT INTO USUARIO VALUES (null, 'CC', '67865656', 'Miguel', '', 'Shinoda', 'Goku', 'mike.shindoa@gmail.com', '675574554', 'img/mike.jpg', 'activo', '3be76c0e963a343cd25f38dd92649ed2', 3);

-- inserts para VEHICULO
insert into VEHICULO values (null, 'ABC123', 'rojo', '2020', 'Toyota', 'Carro', 1);
insert into VEHICULO values (null, 'GHT124', 'azul', '2011', 'Chevrolet', 'Carro', 2);
insert into VEHICULO values (null, 'EWX125', 'oro azucar', '2000', 'Hyundai', 'Carro', 3);
insert into VEHICULO values (null, 'ABC126', 'mate negro', '2020', 'Nissan', 'Carro', 4);
insert into VEHICULO values (null, 'ABC127', 'rojo perla', '2020', 'Yamaha', 'Moto', 5);
insert into VEHICULO values (null, 'MEA222', 'Negro gotico', '1999', 'BMW', 'Carro', 5);
insert into VEHICULO values (null, 'FDA128', 'rojo tomate', '2020', 'Yamaha', 'Moto', 6); 
insert into VEHICULO values (null, 'FBI129', 'amarillo mostaza', '2020', 'Nissan', 'Carro', 7);
insert into VEHICULO values (null, 'CIA130', 'marron fecal', '2020', 'Toyota', 'Carro', 8);
insert into VEHICULO values (null, 'NHA131', 'blanco  perla', '2020', 'Yamaha', 'Moto', 9);
insert into VEHICULO values (null, 'BMW13', 'Azul Cielo', '2020', 'Nissan', 'Carro', 9);
insert into VEHICULO values (null, 'NSA132', 'rojo sangre', '2020', 'Chevrolet', 'Carro', 10);
insert into VEHICULO values (null, 'CNN133', 'verde limon', '2020', 'Nissan', 'Carro', 11);
insert into VEHICULO values (null, 'EXE134', 'purpura atómico', '2020', 'Chevrolet', 'Carro', 12);
insert into VEHICULO values (null, 'ZIP136', 'rojo', '2020', 'Honda', 'Moto', 14);
insert into VEHICULO values (null, 'DEV135', 'violeta neón', '2020', 'Chevrolet', 'Carro', 13);
insert into VEHICULO values (null, 'GAY137', 'rojo', '2018', 'Toyota', 'Carro', 15);
insert into VEHICULO values (null, 'ORO138', 'rojo', '2015', 'AKT', 'Moto', 16);

--Inserts para PICO_PLACA
insert into PICO_PLACA values (null, 'Carro', '1', 'Lunes');
insert into PICO_PLACA values (null, 'Carro', '2', 'Lunes');
insert into PICO_PLACA values (null, 'Carro', '3', 'Martes');
insert into PICO_PLACA values (null, 'Carro', '4', 'Martes');
insert into PICO_PLACA values (null, 'Carro', '5', 'Miercoles');
insert into PICO_PLACA values (null, 'Carro', '6', 'Miercoles');
insert into PICO_PLACA values (null, 'Carro', '7', 'Jueves');
insert into PICO_PLACA values (null, 'Carro', '8', 'Jueves');
insert into PICO_PLACA values (null, 'Carro', '9', 'Viernes');
insert into PICO_PLACA values (null, 'Carro', '0', 'Viernes');
insert into PICO_PLACA values (null, 'Moto', '1', 'Lunes');
insert into PICO_PLACA values (null, 'Moto', '2', 'Lunes');
insert into PICO_PLACA values (null, 'Moto', '3', 'Martes');
insert into PICO_PLACA values (null, 'Moto', '4', 'Martes');
insert into PICO_PLACA values (null, 'Moto', '5', 'Miercoles');
insert into PICO_PLACA values (null, 'Moto', '6', 'Miercoles');
insert into PICO_PLACA values (null, 'Moto', '7', 'Jueves');
insert into PICO_PLACA values (null, 'Moto', '8', 'Jueves');
insert into PICO_PLACA values (null, 'Moto', '9', 'Viernes');
insert into PICO_PLACA values (null, 'Moto', '0', 'Viernes');

-- inserts para ACCESO_SALIDAS
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 1);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 2', 0, 2);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 3', 0, 3);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 4', 560000, 4);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 1', 0, 5);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 3', 0, 6);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 4', 0, 7);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 8);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 1', 340000, 9);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 1', 260000, 10);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 3', 0, 11);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 4', 0, 12);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 13);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 1', 580000, 14);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 15);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 16);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 1', 0, 4);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 1', 390000, 1);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 3', 0, 7);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 4', 850000, 8);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 4', 0, 12);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 4', 450000, 2);
insert into ACCESO_SALIDAS values (null, 'Entrada', '2025-04-06 19:22:53', 'Puerta 2', 0, 9);
insert into ACCESO_SALIDAS values (null, 'Salida', '2025-04-06 19:22:53', 'Puerta 2', 160000, 5);  

--inserts para INCIDENCIA
insert into INCIDENCIA values (null, 'Robo de vehiculo');
insert into INCIDENCIA values (null, 'Robo de accesorios');
insert into INCIDENCIA values (null, 'Robo de llaves');
insert into INCIDENCIA values (null, 'Robo de documentos');
insert into INCIDENCIA values (null, 'Robo de objetos personales');
insert into INCIDENCIA values (null, 'Robo de dinero');
insert into INCIDENCIA values (null, 'Robo de celular');
insert into INCIDENCIA values (null, 'Robo de computador');
insert into INCIDENCIA values (null, 'Robo de maletín');
insert into INCIDENCIA values (null, 'choque');
insert into INCIDENCIA values (null, 'vehiculo rayado');
insert into INCIDENCIA values (null, 'atropellamiento de personas');
insert into INCIDENCIA values (null, 'atropellamiento de animales');

--insert into REPORTE_INCIDENCIA
insert into REPORTE_INCIDENCIA values (1, 10, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (2, 11, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (3, 10, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (10, 13, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (12, 10, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 10, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 10, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 2, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 11, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 13, '2025-04-06 19:22:53');
insert into REPORTE_INCIDENCIA values (15, 13, '2025-04-06 19:22:53');

--inserts para CELDA
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Carro', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');
insert into CELDA values (null, 'Moto', 'Libre');


--inserts para HISTORIAL_PARQUEO
insert into HISTORIAL_PARQUEO values (1, 1, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (2, 2, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (3, 3, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (4, 4, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (5, 5, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (6, 6, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (7, 7, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (8, 8, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (9, 9, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (10, 10, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (11, 11, '2025-04-06 19:22:53');
insert into HISTORIAL_PARQUEO values (12, 12, '2025-04-06 19:22:53');


--Consulta reporte 1
select * from USUARIO

--Consulta reporte 2
SELECT
vehiculo.placa, 
vehiculo.marca,
VEHICULO.tipo,
vehiculo.color,
USUARIO.numero_documento,
USUARIO.primer_nombre,
USUARIO.primer_apellido
FROM
USUARIO, VEHICULO
WHERE
USUARIO.id_usuario = VEHICULO.USUARIO_id_usuario

--consulta reporte 3
select 
ACCESO_SALIDAS.movimiento,
ACCESO_SALIDAS.fecha_hora,
ACCESO_SALIDAS.puerta,
VEHICULO.placa
FROM
ACCESO_SALIDAS, VEHICULO
WHERE 
ACCESO_SALIDAS.VEHICULO_id = VEHICULO.id
AND
ACCESO_SALIDAS.movimiento = 'entrada'

--consulta reporte 4
select 
ACCESO_SALIDAS.movimiento,
ACCESO_SALIDAS.fecha_hora,
ACCESO_SALIDAS.puerta,
ACCESO_SALIDAS.tiempo_estadia,
VEHICULO.placa
FROM
ACCESO_SALIDAS, VEHICULO
WHERE 
ACCESO_SALIDAS.VEHICULO_id = VEHICULO.id
AND
ACCESO_SALIDAS.movimiento = 'salida'

--consulta reporte 5
select 
INCIDENCIA.nombre,
REPORTE_INCIDENCIA.fecha_hora,
VEHICULO.placa
FROM
INCIDENCIA, REPORTE_INCIDENCIA, VEHICULO
WHERE
REPORTE_INCIDENCIA.INCIDENCIA_id = INCIDENCIA.id
AND
VEHICULO.id = REPORTE_INCIDENCIA.VEHICULO_id

--consulta reporte 6
select 
INCIDENCIA.nombre,
REPORTE_INCIDENCIA.fecha_hora,
VEHICULO.placa,
USUARIO.primer_nombre,
USUARIO.primer_apellido,
USUARIO.numero_celular,
USUARIO.direccion_correo
FROM
INCIDENCIA, REPORTE_INCIDENCIA, VEHICULO, USUARIO
WHERE
REPORTE_INCIDENCIA.INCIDENCIA_id = INCIDENCIA.id
AND
VEHICULO.id = REPORTE_INCIDENCIA.VEHICULO_id
AND
VEHICULO.USUARIO_id_usuario = USUARIO.id_usuario